# Generated by Django 5.2.3 on 2025-07-01 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0001_initial'),
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='student',
            new_name='students',
        ),
        migrations.AddField(
            model_name='section',
            name='subjects',
            field=models.ManyToManyField(to='subject.subject'),
        ),
    ]
