# Generated by Django 5.2.3 on 2025-07-03 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='activity/'),
        ),
    ]
