# Generated by Django 5.2.3 on 2025-07-03 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_alter_activity_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitysubmission',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='submission/'),
        ),
    ]
